name: prereqs-build-checking
on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies Instalation
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential
          sudo make prereqs
      - name: Building
        run: |
          sudo make build
      - name: Testing
        run: |
          sudo make test
